<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
	<Version>7.1.1</Version>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.6.1.7" />
  </ItemGroup>
  <ItemGroup>
  <AndroidLibrary Update="apptentive-message-center-7.1.1.aar">
    <Bind>true</Bind>
    <Pack>true</Pack>
  </AndroidLibrary>
</ItemGroup>
</Project>