<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
     <Version>7.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Additions\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Additions\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.6.1.7" />
    <PackageReference Include="GoogleGson" Version="2.10.1.8" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.23" />
    <PackageReference Include="Xamarin.Kotlin.StdLib" Version="1.9.23" />
    <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.6.2.2" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.7.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.7.0.1" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.10.0.3" />
    <PackageReference Include="Xamarin.GooglePlayServices.Base" Version="118.2.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Xamarin.AndroidX.Fragment" Version="1.6.2.2" />
	  <PackageReference Include="Xamarin.Google.Android.Play.Review" Version="2.0.1.7" />
	  <PackageReference Include="Xamarin.Google.Android.Play.Review.Ktx" Version="2.0.1.7"/>
<!--     <PackageReference Include="ApptentiveMessageCenter" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveRatings" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveNotes" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveSurvey" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveEnjoymentDialog" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveNavigateToLink" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveInAppReview" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveInitiator" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveCoreUI" Version="7.0.0"/> -->
<!--     <PackageReference Include="ApptentiveCore" Version="7.0.0"/> -->

    <!-- Dev options to work with the local changes	   -->
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveCore\ApptentiveCore\ApptentiveCore.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveCoreUI\ApptentiveCoreUI\ApptentiveCoreUI.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveEnjoymentDialog\ApptentiveEnjoymentDialog\ApptentiveEnjoymentDialog.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveInAppReview\ApptentiveInAppReview\ApptentiveInAppReview.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveMessageCenter\ApptentiveMessageCenter\ApptentiveMessageCenter.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveNavigateToLink\ApptentiveNavigateToLink\ApptentiveNavigateToLink.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveNotes\ApptentiveNotes\ApptentiveNotes.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveRatings\ApptentiveRatings\ApptentiveRatings.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveSurvey\ApptentiveSurvey\ApptentiveSurvey.csproj" />
    <ProjectReference Include="..\..\..\ApptentiveKit.Android\ApptentiveInitiator\ApptentiveInitiator\ApptentiveInitiator.csproj" />
  </ItemGroup>
<ItemGroup>
  <AndroidLibrary Update="apptentive-feedback-7.0.0.aar">
    <Bind>true</Bind>
    <Pack>true</Pack>
  </AndroidLibrary>
</ItemGroup>
</Project>