<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
	<Version>7.0.0</Version>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.ConstraintLayout" Version="2.1.4.10" />
  </ItemGroup>
  <ItemGroup>
  <AndroidLibrary Update="apptentive-notes-7.0.0.aar">
    <Bind>true</Bind>
    <Pack>true</Pack>
  </AndroidLibrary>
</ItemGroup>
</Project>